# ─────────────────────────────────────────────────────────
# Site Settings
# ─────────────────────────────────────────────────────────
title: "Hyeonjong Jang"
email: ""
description: "Academic portfolio and research blog."
url: ""            # 예: https://hyeonjongjang.github.io (사용 시 기입)
baseurl: ""        # 사용자 페이지면 빈 문자열 유지
repository: ""     # 예: HyeonjongJang/HyeonjongJang.github.io
locale: "en-US"

# ─────────────────────────────────────────────────────────
# Build Settings (Minimal Mistakes with remote_theme)
# ─────────────────────────────────────────────────────────
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-archives
  - jekyll-redirect-from
  - jemoji

paginate: 5
paginate_path: /page:num/

# ─────────────────────────────────────────────────────────
# Collections
# ─────────────────────────────────────────────────────────
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  history:               # ✅ NEW: 커리어 히스토리 컬렉션
    output: true
    permalink: /:collection/:path/

# ─────────────────────────────────────────────────────────
# Defaults (Layouts / Author profile / etc.)
# ─────────────────────────────────────────────────────────
defaults:
  # 페이지
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true

  # 포스트(블로그)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  # Teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true

  # Publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

  # Portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

  # Talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true

  # ✅ History (NEW)
  - scope:
      path: ""
      type: history
    values:
      layout: single
      author_profile: true
      share: true
      comments: false

# ─────────────────────────────────────────────────────────
# Archive (Minimal Mistakes)
# ─────────────────────────────────────────────────────────
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ─────────────────────────────────────────────────────────
# Author (필요 시 수정)
# ─────────────────────────────────────────────────────────
author:
  name: "Hyeonjong Jang"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "AI Researcher"
  location: "Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/HyeonjongJang"

# ─────────────────────────────────────────────────────────
# Exclude / Include
# ─────────────────────────────────────────────────────────
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md

include:
  - _pages

# ─────────────────────────────────────────────────────────
# Permalinks
# ─────────────────────────────────────────────────────────
permalink: /:categories/:title/
