# ─────────────────────────────────────────────────────────
# Site Settings
# ─────────────────────────────────────────────────────────
title: "Hyeonjong Jang"
email: ""
description: "Academic portfolio and research blog."
url: "https://hyeonjongjang.github.io"          # ✅ GitHub 사용자 페이지 URL
baseurl: ""                                      # ✅ 사용자/Org 페이지면 빈 문자열
repository: "HyeonjongJang/HyeonjongJang.github.io"  # ✅ jekyll-github-metadata용

locale: "en-US"
timezone: "Asia/Seoul"

# ─────────────────────────────────────────────────────────
# Theme / Build
# ─────────────────────────────────────────────────────────
remote_theme: "mmistakes/minimal-mistakes"

markdown: kramdown
highlighter: rouge

# GitHub Pages에서 허용되는 플러그인들 중심
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives      # ✅ 빌드 실패 원인 플러그인
  - jekyll-remote-theme  # remote_theme 사용 시 안전

paginate: 5
paginate_path: /page:num/

# ─────────────────────────────────────────────────────────
# Collections
# ─────────────────────────────────────────────────────────
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  history:               # ✅ 새 커리어 히스토리 컬렉션
    output: true
    permalink: /:collection/:path/

# ─────────────────────────────────────────────────────────
# Defaults (Layouts / Author profile / etc.)
# ─────────────────────────────────────────────────────────
defaults:
  # Pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true

  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  # Teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true

  # Publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

  # Portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true

  # Talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true

  # ✅ History
  - scope:
      path: ""
      type: history
    values:
      layout: single
      author_profile: true
      share: true
      comments: false

# ─────────────────────────────────────────────────────────
# Archives (if needed with jekyll-archives)
# ─────────────────────────────────────────────────────────
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ─────────────────────────────────────────────────────────
# Author
# ─────────────────────────────────────────────────────────
author:
  name: "Hyeonjong Jang"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "AI Researcher"
  location: "Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/HyeonjongJang"

# ─────────────────────────────────────────────────────────
# Exclude / Include
# ─────────────────────────────────────────────────────────
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md

include:
  - _pages

# ─────────────────────────────────────────────────────────
# Permalinks
# ─────────────────────────────────────────────────────────
permalink: /:categories/:title/
